### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by kelden** [mikeseven/node-glfw#24]
Got the following error when trying to run test/test.js. [Using Dependency Walker](http://www.dependencywalker.com/) on Release\glfw.node showed that I was missing  vcruntime140.dll. After installing the [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-ca/download/details.aspx?id=48145) everything worked fine. It does make me wonder how that ended up as a dependency, given that the visual studio solution was generated on my computer and not part of the git tree. It must be some issue with node-gyp? Anyways, I'm just posting this here in case some else has similar issues. Maybe list "the most current visual c++ redistributable" as a dependency on the readme.md?

```
snip@snip ~/Documents/src/nodejs/glfw-test/node_modules/node-glfw
$ node test/test.js
c:\Users\snip\Documents\src\nodejs\glfw-test\node_modules\bindings\bindings.js
:83
        throw e
        ^

Error: The specified module could not be found.
\\?\c:\Users\snip\Documents\src\nodejs\glfw-test\node_modules\node-glfw\build\
Release\glfw.node
    at Error (native)
    at Object.Module._extensions..node (module.js:424:18)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at bindings (c:\Users\snip\Documents\src\nodejs\glfw-test\node_modules\bin
dings\bindings.js:76:44)
    at Object.<anonymous> (c:\Users\snip\Documents\src\nodejs\glfw-test\node_m
odules\node-glfw\index.js:1:48)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
```

**Comment by kelden** [comment]
After reading the [readme.md for node-native-graphics-deps](https://github.com/mikeseven/node-native-graphics-deps) all of this makes more sense. I still think the readme should be updated to more clearly state that you do not need to download the individual dependencies on windows, but you do need to install vc2015.

Thanks, Kelden.

**Comment by mikeseven** [comment]
You don’t need to install VC2015. It also works with 2012, 2013.
But obviously, in order to compile native code (C/C++), you need a compiler like Visual Studio.

OK I’ll update the readme.

Thanks,

On Dec 9, 2015, at 3:08 PM, kelden <notifications@github.com<mailto:notifications@github.com>> wrote:


After reading the readme.md for node-native-graphics-deps<https://github.com/mikeseven/node-native-graphics-deps> all of this makes more sense. I still think the readme should be updated to more clearly state that you do not need to download the individual dependencies on windows, but you do need to install vc2015.

Thanks, Kelden.

**Comment by mikeseven** [comment]
BTW, it is already mentioned in the readme for windows that I use VS2013 and 2015…

On Dec 9, 2015, at 3:08 PM, kelden <notifications@github.com<mailto:notifications@github.com>> wrote:


After reading the readme.md for node-native-graphics-deps<https://github.com/mikeseven/node-native-graphics-deps> all of this makes more sense. I still think the readme should be updated to more clearly state that you do not need to download the individual dependencies on windows, but you do need to install vc2015.

Thanks, Kelden.

**Comment by kelden** [comment]
I already had VS2013 installed as well as visual c++ 2013. What was missing was the 2015 c++ libraries because of the prebuilt binaries that are included. Not a big deal, it was an easy fix. Thanks Mike.

**Comment by mikeseven** [comment]
oops yes indeed. I should update the readme for that!!!!

On Dec 9, 2015, at 5:20 PM, kelden <notifications@github.com<mailto:notifications@github.com>> wrote:


I already had VS2013 installed as well as visual c++ 2013. What was missing was the 2015 c++ libraries because of the prebuilt binaries that are included. Not a big deal, it was an easy fix. Thanks Mike.
