### ISSUE TITLE
Issue in the test_atb.js

### ISSUE THREAD

**Issue by AndreyArsov** [mikeseven/node-glfw#25]
There is a bug in the javascript, creating new bar should be done with

twBar=ATB.NewBar("Cube");

instead of using a constructor

twBar=new ATB.NewBar("Cube");

**Comment by mikeseven** [comment]
Thanks good catch.

--mike



On Sat, Mar 12, 2016 at 7:11 PM -0800, "AndreyArsov" <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a bug in the javascript, creating new bar should be done with

twBar=ATB.NewBar("Cube");

instead of using a constructor

twBar=new ATB.NewBar("Cube");

-

**Comment by AndreyArsov** [comment]
Btw great library. Very easy for showing client usage in node.

Thanks for putting the effort

Andrey.

Andrey (phone)

-----Original Message-----

**Comment by mikeseven** [comment]
fixed, thanks!
